services:

  nginx:
    image: nginx:alpine
    container_name: project07-nginx

    ports:
      - "8080:80"

    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d

    depends_on:
      - php

    networks:
      - app

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile

    container_name: project07-php

    volumes:
      - ./src:/var/www/html

    networks:
      - app

networks:
  app:
