name: Deploy Project 07 Agustus

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd /var/www/html/project_07_agustus

            echo "=== UPDATE SOURCE CODE ==="

            git fetch origin
            git reset --hard origin/main

            echo "=== DEPLOYMENT BERHASIL ==="

            git log -1 --oneline